services:
  jenkins-master:
    image: jenkins/jenkins:latest
    container_name: jenkins-master
    ports:
      - "8080:8080"  # Jenkins web UI port
      - "50000:50000"  # Port for agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Required to run Docker commands
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin

  jenkins-agent:
    image: jenkins/inbound-agent:latest-jdk17  # Official Jenkins agent image
    container_name: jenkins-agent
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=agent-1
      - JENKINS_AGENT_SECRET=your-agent-secret  # Use the real secret from Jenkins master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Required for Docker commands

volumes:
  jenkins_home:
    driver: local
